### ISSUE TITLE
display

### ISSUE THREAD

**Issue by ixkqo** [ApolloRisky/EFI_Clover-Asus-K501LB-Mojave#6]
the screen becomes blurred and indistinct when boot up，have you met？

**Comment by pwn-0x309** [comment]
Yeah, it becomes blurred and indistinct for a while (~5s).
Have you got any trouble? Did your machine boot up successfully? @ixkqo

**Comment by ixkqo** [comment]
When csm is turned off to start, eight apple patterns appear in the progress bar halfway through loading, and then when it comes to the boot interface, the screen becomes blurry and you need to turn on csm to started

**Comment by pwn-0x309** [comment]
Do you have any idea to get rid of this annoying boot issue? 
Could you please send a video record of your machine boot time here?
